#      /$$$$$$  /$$$$$$$$ /$$        /$$$$$$   /$$$$$$        /$$$$$$$$ /$$   /$$  /$$$$$$  /$$   /$$  /$$$$$$  /$$   /$$ /$$$$$$$$ /$$$$$$
#     /$$__  $$|__  $$__/| $$       /$$__  $$ /$$__  $$      | $$_____/| $$$ | $$ /$$__  $$| $$  | $$ /$$__  $$| $$$ | $$|__  $$__//$$__  $$
#    | $$  \ $$   | $$   | $$      | $$  \ $$| $$  \__/      | $$      | $$$$| $$| $$  \__/| $$  | $$| $$  \ $$| $$$$| $$   | $$  | $$  \__/
#    | $$$$$$$$   | $$   | $$      | $$$$$$$$|  $$$$$$       | $$$$$   | $$ $$ $$| $$      | $$$$$$$$| $$$$$$$$| $$ $$ $$   | $$  |  $$$$$$
#    | $$__  $$   | $$   | $$      | $$__  $$ \____  $$      | $$__/   | $$  $$$$| $$      | $$__  $$| $$__  $$| $$  $$$$   | $$   \____  $$
#    | $$  | $$   | $$   | $$      | $$  | $$ /$$  \ $$      | $$      | $$\  $$$| $$    $$| $$  | $$| $$  | $$| $$\  $$$   | $$   /$$  \ $$
#    | $$  | $$   | $$   | $$$$$$$$| $$  | $$|  $$$$$$/      | $$$$$$$$| $$ \  $$|  $$$$$$/| $$  | $$| $$  | $$| $$ \  $$   | $$  |  $$$$$$/
#    |__/  |__/   |__/   |________/|__/  |__/ \______/       |________/|__/  \__/ \______/ |__/  |__/|__/  |__/|__/  \__/   |__/   \______/
#
#    This plugin was made by _Ghillie & Helix
#
#    Plugin Version 1.0
#

