#
#      /$$$$$$  /$$$$$$$$ /$$        /$$$$$$   /$$$$$$        /$$$$$$$$ /$$   /$$  /$$$$$$  /$$   /$$  /$$$$$$  /$$   /$$ /$$$$$$$$ /$$$$$$
#     /$$__  $$|__  $$__/| $$       /$$__  $$ /$$__  $$      | $$_____/| $$$ | $$ /$$__  $$| $$  | $$ /$$__  $$| $$$ | $$|__  $$__//$$__  $$
#    | $$  \ $$   | $$   | $$      | $$  \ $$| $$  \__/      | $$      | $$$$| $$| $$  \__/| $$  | $$| $$  \ $$| $$$$| $$   | $$  | $$  \__/
#    | $$$$$$$$   | $$   | $$      | $$$$$$$$|  $$$$$$       | $$$$$   | $$ $$ $$| $$      | $$$$$$$$| $$$$$$$$| $$ $$ $$   | $$  |  $$$$$$
#    | $$__  $$   | $$   | $$      | $$__  $$ \____  $$      | $$__/   | $$  $$$$| $$      | $$__  $$| $$__  $$| $$  $$$$   | $$   \____  $$
#    | $$  | $$   | $$   | $$      | $$  | $$ /$$  \ $$      | $$      | $$\  $$$| $$    $$| $$  | $$| $$  | $$| $$\  $$$   | $$   /$$  \ $$
#    | $$  | $$   | $$   | $$$$$$$$| $$  | $$|  $$$$$$/      | $$$$$$$$| $$ \  $$|  $$$$$$/| $$  | $$| $$  | $$| $$ \  $$   | $$  |  $$$$$$/
#    |__/  |__/   |__/   |________/|__/  |__/ \______/       |________/|__/  \__/ \______/ |__/  |__/|__/  |__/|__/  \__/   |__/   \______/
#
#    This plugin was made by _Ghillie
#
#    Plugin Version 1.3.2
#
#    Discord: https://discord.gg/f9swPR7NnV
#

Command-Messages:
  ##########################################################
  #                                                        #
  #                   DEFAULT MESSAGES                     #
  #                                                        #
  ##########################################################
  Command-Messages-UnknownCommand:
    - "&c&m&l------------&f&l [&x&F&F&3&C&3&C&lA&x&F&F&4&C&3&E&lt&x&F&E&5&C&4&0&ll&x&F&E&6&C&4&2&la&x&F&E&7&C&4&4&ls &x&F&D&8&C&4&6&lE&x&F&D&9&C&4&8&ln&x&F&D&A&B&4&A&lc&x&F&C&B&B&4&C&lh&x&F&C&C&B&4&E&la&x&F&C&D&B&5&0&ln&x&F&B&E&B&5&2&lt&x&F&B&F&B&5&4&ls&f&l] &c&m&l-------------"
    - ""
    - "&c● &7This command is not recognised."
    - ""
    - "&c&m&l-----------------------------------------"
  Command-Messages-NoPermissions:
    - "&c&m&l------------&f&l [&x&F&F&3&C&3&C&lA&x&F&F&4&C&3&E&lt&x&F&E&5&C&4&0&ll&x&F&E&6&C&4&2&la&x&F&E&7&C&4&4&ls &x&F&D&8&C&4&6&lE&x&F&D&9&C&4&8&ln&x&F&D&A&B&4&A&lc&x&F&C&B&B&4&C&lh&x&F&C&C&B&4&E&la&x&F&C&D&B&5&0&ln&x&F&B&E&B&5&2&lt&x&F&B&F&B&5&4&ls&f&l] &c&m&l-------------"
    - ""
    - "&c● &7You do not have the correct &cPermissions &7or you are not &cOped&7."
    - ""
    - "&c&m&l-----------------------------------------"
  Command-Messages-NotAPlayer:
    - "&c&m&l------------&f&l [&x&F&F&3&C&3&C&lA&x&F&F&4&C&3&E&lt&x&F&E&5&C&4&0&ll&x&F&E&6&C&4&2&la&x&F&E&7&C&4&4&ls &x&F&D&8&C&4&6&lE&x&F&D&9&C&4&8&ln&x&F&D&A&B&4&A&lc&x&F&C&B&B&4&C&lh&x&F&C&C&B&4&E&la&x&F&C&D&B&5&0&ln&x&F&B&E&B&5&2&lt&x&F&B&F&B&5&4&ls&f&l] &c&m&l-------------"
    - ""
    - "&c● &7This command can only be used by players."
    - ""
    - "&c&m&l-----------------------------------------"
  ##########################################################
  #                                                        #
  #                RELOAD CONFIG MESSAGES                  #
  #                                                        #
  ##########################################################
  Command-Messages-ReloadConfig-ConfigReloaded:
    - "&c&m&l------------&f&l [&x&F&F&3&C&3&C&lA&x&F&F&4&C&3&E&lt&x&F&E&5&C&4&0&ll&x&F&E&6&C&4&2&la&x&F&E&7&C&4&4&ls &x&F&D&8&C&4&6&lE&x&F&D&9&C&4&8&ln&x&F&D&A&B&4&A&lc&x&F&C&B&B&4&C&lh&x&F&C&C&B&4&E&la&x&F&C&D&B&5&0&ln&x&F&B&E&B&5&2&lt&x&F&B&F&B&5&4&ls&f&l] &c&m&l-------------"
    - ""
    - "&c● &7You have &aReloaded &7the config."
    - ""
    - "&c&m&l-----------------------------------------"
  ##########################################################
  #                                                        #
  #                 GIVE ENCHANT MESSAGES                  #
  #                                                        #
  ##########################################################
  Command-Messages-GiveEnchant-Usage-Message:
    - "&c&m&l------------&f&l [&x&F&F&3&C&3&C&lA&x&F&F&4&C&3&E&lt&x&F&E&5&C&4&0&ll&x&F&E&6&C&4&2&la&x&F&E&7&C&4&4&ls &x&F&D&8&C&4&6&lE&x&F&D&9&C&4&8&ln&x&F&D&A&B&4&A&lc&x&F&C&B&B&4&C&lh&x&F&C&C&B&4&E&la&x&F&C&D&B&5&0&ln&x&F&B&E&B&5&2&lt&x&F&B&F&B&5&4&ls&f&l] &c&m&l-------------"
    - ""
    - "&c● &7Usage: &c/giveenchant &e<player> <enchant> <level> <amount>"
    - ""
    - "&c&m&l-----------------------------------------"
  Command-Messages-GiveEnchant-PlayerNotFound-Message:
    - "&c&m&l------------&f&l [&x&F&F&3&C&3&C&lA&x&F&F&4&C&3&E&lt&x&F&E&5&C&4&0&ll&x&F&E&6&C&4&2&la&x&F&E&7&C&4&4&ls &x&F&D&8&C&4&6&lE&x&F&D&9&C&4&8&ln&x&F&D&A&B&4&A&lc&x&F&C&B&B&4&C&lh&x&F&C&C&B&4&E&la&x&F&C&D&B&5&0&ln&x&F&B&E&B&5&2&lt&x&F&B&F&B&5&4&ls&f&l] &c&m&l-------------"
    - ""
    - "&c● &7Player Not Found"
    - ""
    - "&c&m&l-----------------------------------------"
  Command-Messages-GiveEnchant-EnchantmentNotFound-Message:
    - "&c&m&l------------&f&l [&x&F&F&3&C&3&C&lA&x&F&F&4&C&3&E&lt&x&F&E&5&C&4&0&ll&x&F&E&6&C&4&2&la&x&F&E&7&C&4&4&ls &x&F&D&8&C&4&6&lE&x&F&D&9&C&4&8&ln&x&F&D&A&B&4&A&lc&x&F&C&B&B&4&C&lh&x&F&C&C&B&4&E&la&x&F&C&D&B&5&0&ln&x&F&B&E&B&5&2&lt&x&F&B&F&B&5&4&ls&f&l] &c&m&l-------------"
    - ""
    - "&c● &7Enchantment Not Found"
    - ""
    - "&c&m&l-----------------------------------------"
  Command-Messages-GiveEnchant-InvalidLevel-Message:
    - "&c&m&l------------&f&l [&x&F&F&3&C&3&C&lA&x&F&F&4&C&3&E&lt&x&F&E&5&C&4&0&ll&x&F&E&6&C&4&2&la&x&F&E&7&C&4&4&ls &x&F&D&8&C&4&6&lE&x&F&D&9&C&4&8&ln&x&F&D&A&B&4&A&lc&x&F&C&B&B&4&C&lh&x&F&C&C&B&4&E&la&x&F&C&D&B&5&0&ln&x&F&B&E&B&5&2&lt&x&F&B&F&B&5&4&ls&f&l] &c&m&l-------------"
    - ""
    - "&c● &7Invalid Level, Level must be between &e1 &7and &e{enchantMaxLvl}"
    - ""
    - "&c&m&l-----------------------------------------"
  Command-Messages-GiveEnchant-LevelRange-Message:
    - "&c&m&l------------&f&l [&x&F&F&3&C&3&C&lA&x&F&F&4&C&3&E&lt&x&F&E&5&C&4&0&ll&x&F&E&6&C&4&2&la&x&F&E&7&C&4&4&ls &x&F&D&8&C&4&6&lE&x&F&D&9&C&4&8&ln&x&F&D&A&B&4&A&lc&x&F&C&B&B&4&C&lh&x&F&C&C&B&4&E&la&x&F&C&D&B&5&0&ln&x&F&B&E&B&5&2&lt&x&F&B&F&B&5&4&ls&f&l] &c&m&l-------------"
    - ""
    - "&c● &7Level must be between &e1 &7and &e{enchantMaxLvl}"
    - ""
    - "&c&m&l-----------------------------------------"
  Command-Messages-GiveEnchant-InvalidAmount-Message:
    - "&c&m&l------------&f&l [&x&F&F&3&C&3&C&lA&x&F&F&4&C&3&E&lt&x&F&E&5&C&4&0&ll&x&F&E&6&C&4&2&la&x&F&E&7&C&4&4&ls &x&F&D&8&C&4&6&lE&x&F&D&9&C&4&8&ln&x&F&D&A&B&4&A&lc&x&F&C&B&B&4&C&lh&x&F&C&C&B&4&E&la&x&F&C&D&B&5&0&ln&x&F&B&E&B&5&2&lt&x&F&B&F&B&5&4&ls&f&l] &c&m&l-------------"
    - ""
    - "&c● &7Invalid Amount, You can only spawn in &e1-64 &7at a time."
    - ""
    - "&c&m&l-----------------------------------------"
  Command-Messages-GiveEnchant-AmountRange-Message:
    - "&c&m&l------------&f&l [&x&F&F&3&C&3&C&lA&x&F&F&4&C&3&E&lt&x&F&E&5&C&4&0&ll&x&F&E&6&C&4&2&la&x&F&E&7&C&4&4&ls &x&F&D&8&C&4&6&lE&x&F&D&9&C&4&8&ln&x&F&D&A&B&4&A&lc&x&F&C&B&B&4&C&lh&x&F&C&C&B&4&E&la&x&F&C&D&B&5&0&ln&x&F&B&E&B&5&2&lt&x&F&B&F&B&5&4&ls&f&l] &c&m&l-------------"
    - ""
    - "&c● &7You can only spawn in &e1-64 &7at a time."
    - ""
    - "&c&m&l-----------------------------------------"

EnchantItems:
  #Type of Item the Enchantments will be.
  EnchantItem: ENCHANTED_BOOK
  #This chance determines if it should run the spawning enchant logic to spawn an enchantment
  #Default Spawn Chance = 0.05 (0.05 = 5% chance that it will allow the spawning system to loop through all the enchants)
  #if the spawning chance fails no enchantment attempt to be spawned.
  EnchantItem-Spawn-Chance: 0.05
  #A list of all rarity's in the plugin. (0.5 = 50%)
  EnchantItem-Rarity-List:
    #Chance to get a Godly enchantment.
    GODLY: 0.05
    #Chance to get a Legendary enchantment.
    LEGENDARY: 0.15
    #Chance to get a Epic enchantment.
    EPIC: 0.30
    #Chance to get a Rare enchantment.
    RARE: 0.5
  #This allows you to flip the order of the enchants default is true, which means it will check all Rares all the way up to Godly#
  #if false then it will check Godly first and make its way down to Rares.
  EnchantItem-Flip-List: true

#The sound that will play when the player applies a new enchant to an item.
#https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html < list of all sounds in minecraft.
EnchantItemSounds:
  #------------------APPLYING ENCHANT SOUNDS------------------#
  #If True the custom enchant apply sound will play.
  EnchantItem-Apply-Sound-Toggle: true
  #The sound that plays when applying a custom enchant.
  EnchantItem-Apply-Sound: BLOCK_AMETHYST_BLOCK_BREAK
  #The volume the sound that plays at when applying a custom enchant.
  EnchantItem-Apply-Volume: 1
  #The pitch the sound that plays at when applying a custom enchant.
  EnchantItem-Apply-Pitch: 0.1
  #------------------ENCHANT ALREADY APPLIED SOUNDS------------------#
  #If True the custom enchant apply sound will play.
  EnchantItem-AlreadyApplied-Sound-Toggle: true
  #The sound that plays when a custom enchant is already applied.
  EnchantItem-AlreadyApplied-Sound: ENTITY_IRON_GOLEM_REPAIR
  #The volume the sound that plays when a custom enchant is already applied.
  EnchantItem-AlreadyApplied-Volume: 1
  #The pitch the sound that plays when a custom enchant is already applied.
  EnchantItem-AlreadyApplied-Pitch: 0.1
  #------------------BLACK LISTED SOUNDS------------------#
  #If True the custom enchant apply sound will play.
  EnchantItem-Blacklisted-Sound-Toggle: true
  #The sound that plays when a blacklisted enchant is found.
  EnchantItem-Blacklisted-Sound: BLOCK_ANVIL_LAND
  #The volume the sound that plays when a blacklisted enchant is found.
  EnchantItem-Blacklisted-Volume: 1
  #The pitch the sound that plays when a blacklisted enchant is found.
  EnchantItem-Blacklisted-Pitch: 0.1
  #------------------DISABLED ENCHANT SOUNDS------------------#
  #If True the custom enchant apply sound will play.
  EnchantItem-DisabledEnchant-Sound-Toggle: true
  #The sound that plays when a blacklisted enchant is found.
  EnchantItem-DisabledEnchant-Sound: BLOCK_ANVIL_LAND
  #The volume the sound that plays when a blacklisted enchant is found.
  EnchantItem-DisabledEnchant-Volume: 1
  #The pitch the sound that plays when a blacklisted enchant is found.
  EnchantItem-DisabledEnchant-Pitch: 0.1

EnchantItemMessages:
  #------------------APPLYING ENCHANT Message------------------#
  #If True the success message will be sent to the player.
  EnchantItem-Success-Message-Toggle: true
  #The message that will be sent when applying a custom enchant to an item.
  EnchantItem-Success-Message:
    -  "&c&m&l------------&f&l [&x&F&F&3&C&3&C&lA&x&F&F&4&C&3&E&lt&x&F&E&5&C&4&0&ll&x&F&E&6&C&4&2&la&x&F&E&7&C&4&4&ls &x&F&D&8&C&4&6&lE&x&F&D&9&C&4&8&ln&x&F&D&A&B&4&A&lc&x&F&C&B&B&4&C&lh&x&F&C&C&B&4&E&la&x&F&C&D&B&5&0&ln&x&F&B&E&B&5&2&lt&x&F&B&F&B&5&4&ls&f&l] &c&m&l-------------"
    -  ""
    -  "&c● &7You &a&lSuccessfully &7Applied: &e&l{enchantName} &7lvl: &e&l{enchantLevel}"
    -  ""
    -  "&c&m&l-----------------------------------------"
  #------------------ENCHANT ALREADY APPLIED Message------------------#
  #If True the Already Applied message will be sent to the player.
  EnchantItem-AlreadyApplied-Message-Toggle: true
  #The message that will be sent when trying to apply an enchant to an item that has the same enchant already applied.
  EnchantItem-AlreadyApplied-Message:
    -  "&c&m&l------------&f&l [&x&F&F&3&C&3&C&lA&x&F&F&4&C&3&E&lt&x&F&E&5&C&4&0&ll&x&F&E&6&C&4&2&la&x&F&E&7&C&4&4&ls &x&F&D&8&C&4&6&lE&x&F&D&9&C&4&8&ln&x&F&D&A&B&4&A&lc&x&F&C&B&B&4&C&lh&x&F&C&C&B&4&E&la&x&F&C&D&B&5&0&ln&x&F&B&E&B&5&2&lt&x&F&B&F&B&5&4&ls&f&l] &c&m&l-------------"
    -  ""
    -  "&c● &7You cannot apply: &e&l{enchantName} &7lvl: &e&l{enchantLevel}"
    -  ""
    -  "&c● &7Because the item already has &c&l{existingEnchantName} &7applied."
    -  ""
    -  "&c● &7Existing Enchant: &c&l{existingEnchantName} &7has the same or lower level to &e&l{enchantName}"
    -  ""
    -  "&c&m&l-----------------------------------------"
  #------------------BLACK LISTED Message------------------#
  #If True blacklist system will work.
  EnchantItem-Blacklisted-Toggle: true
  #If True the blacklist message will be sent to the player.
  EnchantItem-Blacklisted-Message-Toggle: true
  #The message that will be sent when a blacklisted a custom enchant has been found on the item already.
  EnchantItem-Blacklisted-Message:
    -  "&c&m&l------------&f&l [&x&F&F&3&C&3&C&lA&x&F&F&4&C&3&E&lt&x&F&E&5&C&4&0&ll&x&F&E&6&C&4&2&la&x&F&E&7&C&4&4&ls &x&F&D&8&C&4&6&lE&x&F&D&9&C&4&8&ln&x&F&D&A&B&4&A&lc&x&F&C&B&B&4&C&lh&x&F&C&C&B&4&E&la&x&F&C&D&B&5&0&ln&x&F&B&E&B&5&2&lt&x&F&B&F&B&5&4&ls&f&l] &c&m&l-------------"
    -  ""
    -  "&c● &7You cannot apply: &e&l{enchantName} &7lvl: &e&l{enchantLevel}"
    -  ""
    -  "&c● &7Because there is a &c&lBlacklisted Enchant &7already."
    -  ""
    -  "&c● &7Blacklisted Enchant: &c&l{blackListedEnchantName} &7lvl: &c&l{blackListedEnchantLevel}"
    -  ""
    -  "&c&m&l-----------------------------------------"
  #------------------ENCHANT DISABLED Message------------------#
  #If True blacklist system will work.
  EnchantItem-DisabledEnchant-Toggle: true
  #If True the blacklist message will be sent to the player.
  EnchantItem-DisabledEnchant-Message-Toggle: true
  #The message that will be sent when a blacklisted a custom enchant has been found on the item already.
  EnchantItem-DisabledEnchant-Message:
    -  "&c&m&l------------&f&l [&x&F&F&3&C&3&C&lA&x&F&F&4&C&3&E&lt&x&F&E&5&C&4&0&ll&x&F&E&6&C&4&2&la&x&F&E&7&C&4&4&ls &x&F&D&8&C&4&6&lE&x&F&D&9&C&4&8&ln&x&F&D&A&B&4&A&lc&x&F&C&B&B&4&C&lh&x&F&C&C&B&4&E&la&x&F&C&D&B&5&0&ln&x&F&B&E&B&5&2&lt&x&F&B&F&B&5&4&ls&f&l] &c&m&l-------------"
    -  ""
    -  "&c● &7You cannot apply: &e&l{disabledEnchantName} &7lvl: &e&l{disabledEnchantLevel}"
    -  ""
    -  "&c● &7Because that &cEnchant &7is currently &cDisabled&7."
    -  ""
    -  "&c&m&l-----------------------------------------"