#
#      /$$$$$$  /$$$$$$$$ /$$        /$$$$$$   /$$$$$$        /$$$$$$$$ /$$   /$$  /$$$$$$  /$$   /$$  /$$$$$$  /$$   /$$ /$$$$$$$$ /$$$$$$
#     /$$__  $$|__  $$__/| $$       /$$__  $$ /$$__  $$      | $$_____/| $$$ | $$ /$$__  $$| $$  | $$ /$$__  $$| $$$ | $$|__  $$__//$$__  $$
#    | $$  \ $$   | $$   | $$      | $$  \ $$| $$  \__/      | $$      | $$$$| $$| $$  \__/| $$  | $$| $$  \ $$| $$$$| $$   | $$  | $$  \__/
#    | $$$$$$$$   | $$   | $$      | $$$$$$$$|  $$$$$$       | $$$$$   | $$ $$ $$| $$      | $$$$$$$$| $$$$$$$$| $$ $$ $$   | $$  |  $$$$$$
#    | $$__  $$   | $$   | $$      | $$__  $$ \____  $$      | $$__/   | $$  $$$$| $$      | $$__  $$| $$__  $$| $$  $$$$   | $$   \____  $$
#    | $$  | $$   | $$   | $$      | $$  | $$ /$$  \ $$      | $$      | $$\  $$$| $$    $$| $$  | $$| $$  | $$| $$\  $$$   | $$   /$$  \ $$
#    | $$  | $$   | $$   | $$$$$$$$| $$  | $$|  $$$$$$/      | $$$$$$$$| $$ \  $$|  $$$$$$/| $$  | $$| $$  | $$| $$ \  $$   | $$  |  $$$$$$/
#    |__/  |__/   |__/   |________/|__/  |__/ \______/       |________/|__/  \__/ \______/ |__/  |__/|__/  |__/|__/  \__/   |__/   \______/
#
#    This plugin was made by _Ghillie & Helix
#
#    Plugin Version 1.0
#

EnchantItems:
  #Type of Item the Enchant is
  CustomItem: ENCHANTED_BOOK
  #The sound that will play when the player applies a new enchant to an item.
  CustomItemSound: BLOCK_ANVIL_USE

Enchantments:
  FEARSIGHT:
    #Max Level of this enchant (Make sure this lines up with radius-of-glowing-# or it won't work so if you have 3 different level types, then the max level is 3)
    Enchantment-MaxLvl: 3
    #Enchant Name
    Enchantment-Title: "&c&lGODLY &7FearSight &e{lvl}"
    #Lore for the Enchant
    Enchantment-Lore:
      - "&c&m&l------------&f&l [&x&F&F&3&C&3&C&lA&x&F&F&4&C&3&E&lt&x&F&E&5&C&4&0&ll&x&F&E&6&C&4&2&la&x&F&E&7&C&4&4&ls &x&F&D&8&C&4&6&lE&x&F&D&9&C&4&8&ln&x&F&D&A&B&4&A&lc&x&F&C&B&B&4&C&lh&x&F&C&C&B&4&E&la&x&F&C&D&B&5&0&ln&x&F&B&E&B&5&2&lt&x&F&B&F&B&5&4&ls&f&l] &c&m&l-------------"
      - ""
      - "&c● &7Enchant Lvl: &c&l{lvl}"
      - ""
      - "&c● &7Range: &c&l{range} blocks"
      - ""
      - "&c● &7This enchantment allows you to &eSee Entities Through Walls"
      - ""
      - "&c&m&l-----------------------------------------"
    #The lore that will be added to the enchanted Item.
    Enchantment-Apply-Lore: "&c● &7{enchantmentName} &eLvl: {lvl}"
    #The Item that the enchantment can be applied to.
    Enchantment-Apply-Item:
      - LEATHER_HELMET
      - CHAINMAIL_HELMET
      - IRON_HELMET
      - GOLDEN_HELMET
      - TURTLE_HELMET
      - DIAMOND_HELMET
      - NETHERITE_HELMET
    #Colour of the Glow per Mob Type
    Hostile-GLOW-Colour: "RED"
    Passive-GLOW-Colour: "GREEN"
    Player-Villager: "WHITE"
    #Radius of how far the glow goes per Tier
    Radius-of-glowing-1: 5
    Radius-of-glowing-2: 10
    Radius-of-glowing-3: 15
    #Cost per Upgrade
    Amount-of-diamonds-to-level-2: 10
    Amount-of-diamonds-to-level-3: 15
  IRONLUNG:
    #Max Level of this enchant (Make sure this lines up with radius-of-glowing-# or it won't work so if you have 3 different level types, then the max level is 3)
    Enchantment-MaxLvl: 1
    #Enchant Name
    Enchantment-Title: "&5&lEPIC &7Iron Lung &e{lvl}"
    #Lore for the Enchant
    Enchantment-Lore:
      - "&c&m&l------------&f&l [&x&F&F&3&C&3&C&lA&x&F&F&4&C&3&E&lt&x&F&E&5&C&4&0&ll&x&F&E&6&C&4&2&la&x&F&E&7&C&4&4&ls &x&F&D&8&C&4&6&lE&x&F&D&9&C&4&8&ln&x&F&D&A&B&4&A&lc&x&F&C&B&B&4&C&lh&x&F&C&C&B&4&E&la&x&F&C&D&B&5&0&ln&x&F&B&E&B&5&2&lt&x&F&B&F&B&5&4&ls&f&l] &c&m&l-------------"
      - ""
      - "&c● &7Enchant Lvl: &c&l{lvl}"
      - ""
      - "&c● &7Time: &c&l{time}s"
      - ""
      - "&c● &7This enchantment allows you to &eBreath Underwater for {time}"
      - ""
      - "&c&m&l-----------------------------------------"
    #The lore that will be added to the enchanted Item.
    Enchantment-Apply-Lore: "&c● &7{enchantmentName} &eLvl: {lvl}"
    #The Item that the enchantment can be applied to.
    Enchantment-Apply-Item:
      - LEATHER_HELMET
      - CHAINMAIL_HELMET
      - IRON_HELMET
      - GOLDEN_HELMET
      - TURTLE_HELMET
      - DIAMOND_HELMET
      - NETHERITE_HELMET
    #Time of how long you can beath underwater per tier (time is in seconds)
    Time-underwater-1: 300
  DEATH:
      #Max Level of this enchant (Make sure this lines up with radius-of-glowing-# or it won't work so if you have 3 different level types, then the max level is 3)
      Enchantment-MaxLvl: 2
      #Enchant Name
      Enchantment-Title: "&c&lGODLY &7Death &e{lvl}"
      #Lore for the Enchant
      Enchantment-Lore:
        - "&c&m&l------------&f&l [&x&F&F&3&C&3&C&lA&x&F&F&4&C&3&E&lt&x&F&E&5&C&4&0&ll&x&F&E&6&C&4&2&la&x&F&E&7&C&4&4&ls &x&F&D&8&C&4&6&lE&x&F&D&9&C&4&8&ln&x&F&D&A&B&4&A&lc&x&F&C&B&B&4&C&lh&x&F&C&C&B&4&E&la&x&F&C&D&B&5&0&ln&x&F&B&E&B&5&2&lt&x&F&B&F&B&5&4&ls&f&l] &c&m&l-------------"
        - ""
        - "&c● &7Enchant Lvl: &c&l{lvl}"
        - ""
        - "&c● &7Time: &c&l{damage} damage"
        - ""
        - "&c● &7This enchantment allows you to &eInstantly kill any mob"
        - ""
        - "&c&m&l-----------------------------------------"
      #The lore that will be added to the enchanted Item.
      Enchantment-Apply-Lore: "&c● &7{enchantmentName} &eLvl: {lvl}"
      #The Item that the enchantment can be applied to.
      Enchantment-Apply-Item:
        - WOODEN_SWORD
        - IRON_SWORD
        - GOLDEN_SWORD
        - DIAMOND_SWORD
        - NETHERITE_SWORD
      #The amount of damage the enchant does.
      Death-Damage-Amount-1: 500
      Death-Damage-Amount-2: 1000