name: AtlasEnchants
main: com.atlasplugins.atlasenchants.Main

version: '1.3.3'
authors: [_Ghillie]

api-version: '1.20'
description: Custom enchant plugin.

# This sets PlaceholderAPI and WorldGuardAPI as an optional dependency for your plugin.
softdepend: [PlaceholderAPI, WorldGuard]

commands:
  atlasenchants:
    description: Atlas Enchants Command
    usage: /atlasenchants [subcommand]
    aliases: [aenchants, ae]

permissions:
  atlasenchants.help:
    description: Permission needed to use the help command.
    default: false
  atlasenchants.reloadconfig:
    description: Permission needed to use the reload command.
    default: false
  atlasenchants.giveenchant:
    description: Permission needed to use the give enchant command.
    default: false
  atlasenchants.giverandomenchant:
    description: Permission needed to use the give random enchant command.
    default: false
  atlasenchants.giveshard:
    description: Permission needed to use the give shard command.
    default: false
  atlasenchants.giveoraclebook:
    description: Permission needed to use the give oracle book command.
    default: false
  atlasenchants.givealtarofcirce:
    description: Permission needed to use the give Alter Of Circe command.
    default: false
  atlasenchants.givescrapofcirce:
    description: Permission needed to use the give scrap of circe's weave command.
    default: false
  atlasenchants.upgrade:
    description: Permission needed to use the upgrade command.
    default: false
  atlasenchants.enchantlist:
    description: Permission needed to use the enchant list command.
    default: false
  atlasenchants.enchantlistgrabber:
    description: Permission needed to be able to grab any enchant from the enchant list menu.
    default: false
