name: AtlasEnchants
version: '1.2'
main: com.atlasplugins.atlasenchants.Main
api-version: '1.20'
description: Custom Enchants
commands:
  giveenchant:
    description: Gives a player any enchantment
  test:
    description: Give Items to test